name: Run Brakeman

on:
  workflow_call:

jobs:
  run-brakeman:
    name: Run Brakeman
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: true

      - name: Run Brakeman
        run: |
          bundle exec brakeman . --except CheckRenderInline --quiet \
            --no-exit-on-warn --no-exit-on-error \
            -o brakeman.json -o brakeman.sarif

      - name: Upload SARIF to GitHub
        if: github.repository_visibility == 'public'
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: brakeman.sarif

      - name: Upload JSON results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: brakeman-json
          path: brakeman.json