name: Run Brakeman

on:
  workflow_call:

jobs:
  run-brakeman:
    name: Run Brakeman
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true

      - name: Run Brakeman
        run: |
          bundle exec brakeman . --except CheckRenderInline --quiet \
            --no-exit-on-warn --no-exit-on-error \
            -o brakeman.json -o brakeman.sarif

      - name: Upload SARIF to GitHub
        if: github.repository_visibility == 'public'
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: brakeman.sarif

      - name: Upload JSON results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: brakeman-json
          path: brakeman.json